# 비동기 프로그래밍

## Callback

비동기 함수를 통해 얻어진 결과를 핸들링 하기 위해 필요

```javascript
function first(callback) {
  let value;

  setTimeout(() => {
    value = { name: "MaxlChan", age: 18 };
    callback(null, value);
  }, 4000);
}

first(function (error, value) {
  if (error) {
    // 데이터 송신이 실패할 가능성은 언제나 있기 때문에, 콜백 함수는 에러를 핸들링할 수 있어야 한다.
  } else {
    console.log(value); // { name: "MaxlChan", age: 18 }
  }
});
```

하지만 순차적으로 실행이 필요할 경우 중첩시켜 표현하는데 에러나 예외처리가 힘들고 복잡도가 증가함(콜백지옥)

```javascript
function first(callback) {
  let value;

  setTimeout(() => {
    value = { name: "MaxlChan", age: 18 };
    callback(null, value);
  }, 4000);
}

first(function callbackOne(error, value) {
  if (error) {
    // ErrorHandling
  } else {
    second(value, function callbackTwo(error, value) {
      if (error) {
        // ErrorHandling
      } else {
        third(value, function callbackThree(error, value) {
          if (error) {
            // ErrorHandling
          } else {
            console.log(
              `Final value is ${value}. Here is end of Callback hell...`
            );
          }
        });
      }
    });
  }
});
```

## Promise

자바스크립트 비동기 처리에 사용되는 객체

정상적으로 기능이 수행되었으면 성공 메세지와 결과값을 전달하고, 문제가 발생한 경우 에러를 전달해줌.

```javascript
function getData(callback) {
  // new Promise() 추가
  return new Promise(function(resolve, reject) {
    $.get('url 주소/products/1', function(response) {
      // 데이터를 받으면 resolve() 호출
      resolve(response);
    });
  });
}

// getData()의 실행이 끝나면 호출되는 then()
getData().then(function(tableData) {
  // resolve()의 결과 값이 여기로 전달됨
  console.log(tableData); // $.get()의 reponse 값이 tableData에 전달됨
});
```

##### Promise의 3가지 State

- Pending(대기) : 비동기 처리 로직이 아직 완료되지 않은 상태

- Fulfilled(이행) : 비동기 처리가 완료되어 프로미스가 결과값을 반환해준 상태

- Rejected(실패) : 비동기 처리가 실패하거나 오류가 발생한 상태

###### Pending

```javascript
new Promise();
```

new Promise() 메서드를 호출하면 Pending 상태가 됨

메서드를 호출할 때 콜백 함수를 선언할 수 있고, 인자는 resolve, reject임.

```javascript
new Promise(function(resolve, reject) {
  // ...
});
```

###### Fulfilled

콜백 함수의 인자 resolve를 실행하면 Fulfilled 상태가 됨

```javascript
new Promise(function(resolve, reject) {
  resolve();
});
```

Fulfilled 상태가 되면 then()을 이용하여 결과 값을 받을 수 있음

```javascript
function getData() {
  return new Promise(function(resolve, reject) {
    var data = 100;
    resolve(data);
  });
}

// resolve()의 결과 값 data를 resolvedData로 받음
getData().then(function(resolvedData) {
  console.log(resolvedData); // 100
});
```

###### Rejected

reject를 호출하면 Rejected 상태가 됨

```javascript
new Promise(function(resolve, reject) {
  reject();
});
```

그리고 Rejected 상태가 되면 실패한 이유 (실패 처리의 결과 값)을 catch()로 받을 수 있음

```javascript
function getData() {
  return new Promise(function(resolve, reject) {
    reject(new Error("Request is failed"));
  });
}

// reject()의 결과 값 Error를 err에 받음
getData().then().catch(function(err) {
  console.log(err); // Error: Request is failed
});
```

##### Promise Chaining

여러개의 프로미스를 연결할 수 있어 콜백 지옥보다 가독성이 좋음

```javascript
new Promise(function(resolve, reject){
  setTimeout(function() {
    resolve(1);
  }, 2000);
})
.then(function(result) {
  console.log(result); // 1
  return result + 10;
})
.then(function(result) {
  console.log(result); // 11
  return result + 20;
})
.then(function(result) {
  console.log(result); // 31
});
```

##### finally

finally 메소드는 Promise의 성공과 실패와 상관 없이 처리만 되면 실행되는 함수

```javascript
const successPromise = new Promise((resolve, reject) => {
  setTimeout(function () {
    resolve("Success");
  }, 3000);
});

successPromise
  .then((value) => `${value} is`)
  .then((secondValue) => {
    throw new Error("Error!!");
  }) // 에러 발생
  .then((thirdValue) => console.log("possible"))
  .catch((error) => {
    console.log(error);
  })
  .finally(() => console.log("chain end"));
// 위 Promise상태가 어떻든 간에 Promise 객체가 반환되었기 때문에 finally 메소드가 무조건적으로 실행 됨.
```

##### Promise.all

Promise.all 메소드는 배열과 같이 순회 가능한 객체를 인자로 받아 배열 안의 프로미스가 모두 이행되면(반드시 프로미스일 필요는 없음), 각각의 프로미스 결과 값을 담은 배열을 결과값으로 새로운 프로미스 객체를 반환

```javascript
const one = new Promise((resolve, reject) => {
  setTimeout(() => resolve("one"), 1000);
});
const two = new Promise((resolve, reject) => {
  setTimeout(() => resolve("two"), 2000);
});
const three = new Promise((resolve, reject) => {
  setTimeout(() => resolve("three"), 3000);
});

Promise.all([one, two, three]).then((val) => console.log(val));
/* 배열 안 모든 프로미스가 이행된 후(약 3초 이후) 각 이행 결과값을 담은 배열을
   결과값으로 갖는 프로미스 객체가 만들어져
   콘솔에는 ["one", "two", "three"]가 출력됨.*/

Promise.all(["Hi", 123, three]).then((val) => console.log(val));
/* 배열 안 요소가 반드시 프로미스가 아닌 경우에도 가능함.
  하지만 이 경우에도 요소 안애 프로미스가 있다면 프로미스가 이행된 이후에 프로미스 객체가 생성됨.*/
```

## async/await

Promise 결과 값을 then, catch를 통해 다루지 않고, 변수에 담아 동기적 코드처럼 작성 가능

await 키워드는 반드시 async 함수 안에서만 사용이 가능하고, Promise 객체를 생성하는 함수 앞에 놓을 수 있다.

자바스크립트가 await 키워드를 만나게 되면 해당 함수가 Promise 상태가 이행(Fulfilled)될 때까지 기다렸다가, 이행되면 결과 값을 반환하고 다음 코드를 실행한다.

```javascript
console.log(1);

const promise = function () {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      console.log(3);
      resolve("two");
    }, 3000);
  });
};

const promiseTwo = function () {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve("one");
    }, 1000);
  });
};

console.log(2);

async function foo() {
  const result = await promise(); // 프라미스가 이행될 때까지 아래 코드로 넘어가지 않음..
  const resultTwo = await promiseTwo(); // 위 코드의 프로미스가 반환될 때까지 대기...

  console.log(resultTwo); // 완료 되면 하단의 코드가 이어서 실행됨

  const parellOne = promise(); // 위 아래 타이머는 동시에 시작됨.
  const parelltwo = promiseTwo(); // 해당 프로미스 이행 값이 먼저 반환됨.(약 1초)

  console.log(await parellOne);
  console.log(await parelltwo); // 먼저 프로미스 객체가 반환되었지만 위 함수가 먼저 실행되어야 실행됨.
}

foo(); // 콘솔에 찍히는 값은 순서대로 1 2 3 "one" 3 "two" "one"
```

비동기 코드지만 동기 흐름처럼 자연스럽게 코드가 이어진다.

##### Error Handling

에러 핸들링을 위해 try catch를 사용할 수 있다.

```javascript
async function getMaster() {
  try {
    const user = await Promise.reject(new Error("Error!!"));
    const name = user.name;  // 아래 코드는 실행되지 않음
    if (name === "chan") {
      return name;
    }
  } catch (error) {
    console.log(error); // "Error!!"를 출력
  }
}
getMaster();
```
